<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="comp-Lenovo-V110-15ISK" name="group(failed)(failed)" tests="1" failures="1" timestamp="28 Aug 2020 11:40:38 GMT" time="1.717" errors="0">
  <testcase name="group_user_with_valid_operator_for_user_ext_id_in_filter" time="1.026" classname="group.GroupUser">
    <failure type="java.lang.AssertionError" message="API return error when valid operator(=) is passed for user_ext_id field in filter. expected [success] but found [error]">
      <![CDATA[java.lang.AssertionError: API return error when valid operator(=) is passed for user_ext_id field in filter. expected [success] but found [error]
	at group.GroupUser.group_user_with_valid_operator_for_user_ext_id_in_filter(GroupUser.java:2179)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- group_user_with_valid_operator_for_user_ext_id_in_filter -->
</testsuite> <!-- group(failed)(failed) -->
